server:
  tomcat:
    max-swallow-size: ${SERVER_TOMCAT_MAX_SWALLOW_SIZE:20MB}
    connection-timeout: ${SERVER_TOMCAT_CONNECTION_TIMEOUT:60000}
  port: ${SERVER_PORT:8081} # 项目启动的端口

spring:
  servlet:
    multipart:
      max-file-size: 10MB        # 单个文件最大大小
      max-request-size: 20MB     # 整个请求最大大小
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev} # 默认激活 dev 本地开发环境

storage:
  type: ${STORAGE_TYPE:minio} # 对象存储类型
