<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.theoyu</groupId>
        <artifactId>thesis</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>thesis-kv</artifactId>
    <!-- 多模块项目需要配置打包方式为 pom -->
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>键值存储服务</description>

    <modules>
        <module>thesis-kv-api</module>
        <module>thesis-kv-biz</module>
    </modules>


</project>