services:
  # NameServer 服务
  namesrv:
    image: apache/rocketmq:5.3.1
    container_name: rocketmq-namesrv
    privileged: true
    ports:
      - "9876:9876"
    volumes:
      # 统一挂载路径
      - "/mnt/e/linux/docker/rocketmq/namesrv/logs:/home/rocketmq/logs"
      - "/mnt/e/linux/docker/rocketmq/namesrv/bin/runserver.sh:/home/rocketmq/rocketmq-5.3.1/bin/runserver.sh"
    command: ["sh", "mqnamesrv"]
    networks:
      - rocketmq_net

  # Broker 服务
  broker:
    image: apache/rocketmq:5.3.1
    container_name: rocketmq-broker
    privileged: true
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
      - "8070:8080"
    volumes:
      # 统一挂载路径
      - "/mnt/e/linux/docker/rocketmq/broker/logs:/home/rocketmq/logs/rocketmqlogs"
      - "/mnt/e/linux/docker/rocketmq/broker/store:/home/rocketmq/store"
      - "/mnt/e/linux/docker/rocketmq/broker/config/broker.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf"
      - "/mnt/e/linux/docker/rocketmq/broker/bin/runbroker.sh:/home/rocketmq/rocketmq-5.3.1/bin/runbroker.sh"
    environment:
      NAMESRV_ADDR: "rocketmq-namesrv:9876"
    command: ["sh", "mqbroker", "-c", "/home/rocketmq/rocketmq-5.3.1/conf/broker.conf"]
    networks:
      - rocketmq_net
    depends_on:
      - namesrv

  # Dashboard 服务
  dashboard:
    image: apacherocketmq/rocketmq-dashboard
    container_name: rocketmq-dashboard
    network_mode: "service:broker"
    environment:
      JAVA_OPTS: "-Xmx200M -Xms200M -Xmn100M -Drocketmq.namesrv.addr=rocketmq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - broker

# 定义网络
networks:
  rocketmq_net:
    name: rocketmq
    driver: bridge
