spring:
  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE:thesis}
    contact-points: ${CASSANDRA_CONTACT_POINTS}
    port: ${CASSANDRA_PORT:9042}
    local-datacenter: ${CASSANDRA_LOCAL_DATACENTER:datacenter1}
